runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT rcdproject.wsgi

automatic_scaling:
  min_num_instances: 1

beta_settings:
  cloud_sql_instances: rcd-instancia-2025:southamerica-east1:instancia-rcd

env_variables:
  DATABASE_URL: postgres://usuario-database-2025:fYh24CZCi4hgKuVPpRdxIiCVVAooAtla8LbyZmZT7Dnu3px6sZWyXAOfiM1JzN-Kw8U@/rcd-database-2025?host=/cloudsql/rcd-instancia-2025:southamerica-east1:instancia-rcd
  SECRET_KEY: "fYh24CZCi4hgKuVPpRdxIiCVVAooAtla8LbyZmZT7Dnu3px6sZWyXAOfiM1JzN-Kw8U"
  GS_BUCKET_NAME: "rcd-bucket-2025"
